---
title: "Discussion"
---

### What is the connection Between the three case studies?

We investigated how ocean health is changing due to climate change related increases in temperature. 

The connecting factor between the three case studies is the overall rise in ocean temperatures due to climate change. These changes are especially severe during El Niño and La Niña events. Temperature affects ocean chemistry, which can further impact different levels of the food chain. Higher ocean temperatures can cause algae blooms or affect concentrations of dissolved chemicals, which alter the ecosystems that marine creatures depend on. Also, higher temperatures are associated with increases in coral bleaching because higher ocean temperatures leads to a decrease in dissolved oxygen. Decreases in dissolved oxygen have been found to cause increased coral bleaching. This decrease in oxygen has been found to cause an increase in coral bleaching. Additionally, temperature can impact fish species that depend on ocean temperatures. Fish species that prefer water of different temperatures will be unable to live within normal ranges as temperatures shift due to climate change. This will likely result in a mismatch of predators, prey, and resources, causing decreases in fish and predator populations.

Additionally, the increase in ocean temperatures will likely increase fish competition intensity beyond normal patterns. Shifting species habitat ranges will result in increased competition, leading to species population decreases. As temperatures increase, ocean chemical concentrations and dissolved oxygen will change, leading to more coral bleaching events. This in turn will affect the myriad species that depend on corals for food and forage. This cycle of shifting chemical concentrations affecting coral bleaching affecting fish populations is a vicious cycle due to anthropogenic (originating in human activity) climate change. 

### Why is this website important?

### What can you do?

The great thing about the ocean and climate change is that we can actually make a huge difference just by changing a some habits! Listed below are just a couple of ideas if you want to help make the oceans healthier.

**Help decrease amount of Greenhouse Gases (GHGs):** GHGs trap heat in the Earth’s atmosphere. This causes an increase in temperature (including ocean temperatures). One way to decrease the amount og GHGs would be to start using hybrid or electric cars. 

**Buy Local and Sustainable Seafood:** Buy locally caught and sustainable seafood. Buying local not only supports the local economy but also decreases the need for boats that emit GHGs. 

**3 R's:** Reduce, reuse, recycle! Throwing out plastics impact lots of marine life if the plastic is sent to a landfill. However, it could also create more GHGs that we don't want if it gets sent to a trash incinerator which is a place that burns trash. 

**Be open to learn:** One of the greatest things that we can do is be open to learning! Whether that means asking questions or doing some research, it is important to learn about the climate related issues. For starters, check out the [USA Environmental Protection Agency](https://www.epa.gov/climate-change), [United Nations](https://www.un.org/en/climatechange/what-is-climate-change), [NASA](https://climate.nasa.gov/), and [National Ocean and Atmospheric Administration](https://www.noaa.gov/education/resource-collections/climate). 


### Future Research/Next Steps

For future research we would Look into ocean health and climate change indicators in more recent years. For example, the coral bleaching data only goes up until 2012 so getting more recent data would add to the story and provide new insights on recent climate change impacts. Similarly, for coral bleaching, we would look more into ocean acidification effects on the number of bleaching events along with El Niño and La Niña. Additionally, if there was unlimited data access, then looking at one specific area instead of the whole world would be interesting. Our trends of the data were seen across the globe but we wonder whether the same trends would be found if we looked at coral bleaching, ocean chemistry, and fish populations in one location.


### Resources
[Environment: How to stop Ocean warming](https://environment.co/how-to-stop-ocean-warming/)
[USA Environmental Protection Agency: Climate Change](https://www.epa.gov/climate-change)
[United Nations: What is climate change?](https://www.un.org/en/climatechange/what-is-climate-change)
[NASA: Global Climate Change](https://climate.nasa.gov/)
[National Ocean and Atmospheric Administration: Climate Resource Collection](https://www.noaa.gov/education/resource-collections/climate)
